version: '3'
services:
  db-test:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: back-deportes-test
    volumes:
      - ./mongo-testing:/data/db
