version: '3'
services:
  db-dev:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: back-deportes
    volumes:
      - ./mongo-development:/data/db
